CREATE DATABASE IF NOT EXISTS Project_Webpro;

USE project_webpro;

CREATE TABLE IF NOT EXISTS user (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EXP INT NOT NULL DEFAULT 0
);

SELECT * FROM user;

CREATE TABLE IF NOT EXISTS tasks (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    TASK VARCHAR(255) NOT NULL,
    LEVEL ENUM('Easy', 'Medium', 'Hard') DEFAULT 'Medium',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

SELECT * FROM tasks;

CREATE TABLE IF NOT EXISTS notes (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    NOTE TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

SELECT * FROM notes;

CREATE TABLE IF NOT EXISTS Achievement (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    ICON VARCHAR(255) NOT NULL,
    COMPLETE BOOL NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

SELECT * FROM Achievement;